### ISSUE TITLE
How to make components remount on Route with Regex 

### ISSUE THREAD

**Issue by lucis** [urban-bot/urban-bot#151]
Hey, first of all, this project is terrific! Congratulations 🎉 

One thing I image it's possible but haven't been able to achieve is to have a "mixed" `isNewMessageEveryRender` behaviour. 

For example, from the Shop example, I've created a "search for {product}" Route to allow users to search for some item.

I want to still preserve the same message when switching Next/Previous products about that search, but if the user send "search for {another-product}" I want to create a new message, and not update the next one. Is that possible?

Thanks

**Comment by ledamint** [comment]
Hi, thanks, glad to know you like it.
I guess it is possible, try to keep `isNewMessageEveryRender` in state and change it before your action.

```js
const [isNewMessageEveryRender, setIsNewMessageEveryRender] = useState(false);

useText(({text}) => {
    setIsNewMessageEveryRender(true);
    // ...
})

function clickNextProduct() {
     setIsNewMessageEveryRender(false);
     // ...    
}

<Image
    isNewMessageEveryRender={isNewMessageEveryRender}
    // ...
/>
```

**Comment by lucis** [comment]
Thanks, @ledamint! I'll try that
