### ISSUE TITLE
Discord messenger support

### ISSUE THREAD

**Issue by ledamint** [urban-bot/urban-bot#75]
Add the opportunity to write discord bot via urban-bot

**Comment by iron-cherep** [comment]
Any chance this will be released soon? 😅

**Comment by ledamint** [comment]
We will make all possible 🙂

**Comment by feremabraz** [comment]
I don't have anything to say except that this library looks **amazing**. Great job! 🥰 
I'm subscribing to this too. 👀

**Comment by zadeviggers** [comment]
Discord now supports slash commands and buttons (among other things) all through an HTTP API, so it should now be possible to implement most of the features that Urban-bot supports on other platforms.

**Comment by ledamint** [comment]
I've added discord to urban-bot, please take a look. I would be glad to receive any feedback.

@iron-cherep @appkaiju @zadeviggers
